package pojo;
// Generated 2017-6-21 18:49:43 by Hibernate Tools 4.3.1



/**
 * Userdata generated by hbm2java
 */
public class Userdata  implements java.io.Serializable {


     private String email;
     private String name;
     private String password;
     private String phone;
     private String address;
     private String synopsis;
     private Integer authority;

    public Userdata() {
    }

	
    public Userdata(String email, String name) {
        this.email = email;
        this.name = name;
    }
    public Userdata(String email, String name, String password, String phone, String address, String synopsis, Integer authority) {
       this.email = email;
       this.name = name;
       this.password = password;
       this.phone = phone;
       this.address = address;
       this.synopsis = synopsis;
       this.authority = authority;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getSynopsis() {
        return this.synopsis;
    }
    
    public void setSynopsis(String synopsis) {
        this.synopsis = synopsis;
    }
    public Integer getAuthority() {
        return this.authority;
    }
    
    public void setAuthority(Integer authority) {
        this.authority = authority;
    }




}


